services:
    - mongodb
    - redis

language: node_js

node_js:
    - stable

dist: xenial

addons:
    snaps:
        - ffmpeg

cache:
    directories:
        - node_modules

before_install:
    - wget wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
    - sudo chmod a+rx /usr/local/bin/yt-dlp

branches:
    only:
        - master
        - develop

install:
    - yarn install

script:
    - yarn test
    - yarn test:e2e
