services:
    - mongodb
    - redis

language: node_js

node_js:
    - stable

dist: xenial

addons:
    snaps:
        - ffmpeg
        - node --channel=14/stable --classic

cache:
    directories:
        - node_modules

before_install:
    - sudo apt update -y
    - sudo apt install software-properties-common -y
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo sudo apt install python3.8
    - sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
    - sudo chmod a+rx /usr/local/bin/yt-dlp

branches:
    only:
        - master
        - develop

install:
    - yarn install

script:
    - yarn test
    - yarn test:e2e
