services:
    - mongodb
    - redis

language: python

python: 3.8

node_js: stable

dist: xenial

addons:
    snaps:
        - ffmpeg

cache:
    directories:
        - node_modules

before_install:
    - sudo apt update -y
    - sudo apt install software-properties-common -y
    - nvm install v14.16.0
    - nvm use v14.16.0

branches:
    only:
        - master
        - develop

install:
    - yarn install

script:
    - yarn test
    - yarn test:e2e
