services:
    - mongodb
    - redis

language: python

python: 3.8

node_js: stable

dist: xenial

addons:
    snaps:
        - ffmpeg

cache:
    directories:
        - node_modules

before_install:
    - nvm install v14.16.0
    - nvm use v14.16.0
    - sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
    - sudo chmod a+rx /usr/local/bin/yt-dlp

branches:
    only:
        - master
        - develop

install:
    - yarn install

script:
    - yarn test
    - yarn test:e2e
