version: "3.8"

services:
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
        depends_on:
            - was

    was:
        build:
            context: ./
        container_name: was
        restart: "unless-stopped"

    redis:
        image: redis:latest
        container_name: redis

    php:
        image: edyan/php:latest
        container_name: php
        restart: always
        volumes:
            - ./errors/404.php:/source/404.php
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: db
        restart: "unless-stopped"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        command: --init-file /data/application/init.sql
        ports:
            - "3306:3306"
        volumes:
            - ./errors/init.sql:/data/application/init.sql
            - /usr/local/var/mysql:/var/lib/mysql

    admin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
